### ISSUE TITLE
Question about the multi-task learning

### ISSUE THREAD

**Issue by heendung** [lorenmt/auto-lambda#1]
Hi,

Thank you so much for sharing the code!

I am trying to reproduce your results and just wanted to double-check if the following command is for multi-task learning, **not** for auxiliary learning:
`python trainer_dense.py --network split --dataset nyuv2 --task all --weight autol --gpu 3`
In other words, this command will give the result of **Split Multi-Task Auto-lambda**?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/20896788/156310550-c1b504a4-cec9-4d75-98fa-2b76058c490f.png">

Thanks!

**Comment by lorenmt** [comment]
This looks correct. In addition, when you launch the code, it should also reprint the multi-task methods and training tasks to help to confirm this.

**Comment by heendung** [comment]
Thank you so much for the quick reply!

If I run `python trainer_dense.py --network split --dataset nyuv2 --task all --weight autol --gpu 0`, I got the following:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/20896788/156443310-fb8f67c9-e347-42c2-a196-d0b851780486.png">

So here, it outputs "**Auxiliary Learning Mode with SPLIT**". Is this just because this code is designed for both multi-task learning and auxiliary learning tasks? Even though "**Auxiliary Learning Mode with SPLIT**" appears, am I currently doing multi-task learning (not auxiliary learning), right?

To do the auxiliary learning (e.g., Segmentation is primary), do I just run the following command?
`python trainer_dense.py --network split --dataset nyuv2 --task seg --weight autol --gpu 0`
just changing "**all**" to "**seg**".

Thanks!

**Comment by lorenmt** [comment]
That's exactly right. 

Because now we consider multi-task learning as a special case of auxiliary learning, for which the auxiliary tasks now to be all training tasks. So when Training tasks and Primary tasks are identical, we are in the multi-task learning setting. That's the biggest contribution of this work, to solve multi-task learning and auxiliary learning in a single framework!

You may also toggle on noise-prediction tasks by '--with_noise', to see how Auto-Lambda can behave differently when we have a very unuseful auxiliary task. 

Let me know if you can reproduce the results, or you have other questions.

**Comment by heendung** [comment]
I see. 

Thank you for the confirmation and the detailed explanation!

**Comment by heendung** [comment]
Hi again,

BTW, I am **very** interested in your improvement on the RLBench tasks!
Would it be possible to share the RLBench code such that I can reproduce its results?

Thank you!

**Comment by lorenmt** [comment]
Hello,

Since RLBench requires third-part software and significantly more complicated data collection, I planned to omit the RLBench code for readability purposes. But I would be happy to help if want to reproduce RLBench tasks or any other robotics-related frameworks.
